import express from 'express';
import cors from 'cors';
import { agent } from './agent';
import { StreamMessage } from './types';

const app = express();
app.use(express.json());
app.use(cors());

app.get('/', (req, res) => {
  res.json({ message: 'Hello World' });
});

// SSE
// special header
// send data in specail format of data stream like event stream

app.post('/chat', async (req, res) => {
  //const { message } = req.body;

  const { query } = req.body;
  console.log(query);

  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
  });

  // setInterval(() => {
  //   res.write('event: ping\n');
  //   res.write(`data: "${query}"\n\n`);
  // }, 1000);

  const result = await agent.stream(
    {
      messages: [
        {
          role: 'user',
          content: `${query}`,
        },
      ],
    },

    {
      configurable: {
        thread_id: 'user-1', // unique id for the user generated by the server TODO
      },
      streamMode: ['messages'],
    },
  );

  for await (const [eventType, chunk] of result) {
    //console.log('eventType', eventType);
    //console.log('chunk', JSON.stringify(chunk[0].content, null, 2));

    let messageType = chunk[0].type;
    let messsage: StreamMessage;

    if (messageType === 'ai') {
      messsage = { type: 'ai', payload: { text: chunk[0].content } };
    } else if (messageType === 'toolCall:start') {
      messsage = {
        type: 'toolCall:start',
        payload: {
          name: chunk[0].tool_call.name,
          args: chunk[0].tool_call.args,
        },
      };
    } else if (messageType === 'tool') {
      messsage = {
        type: 'tool',
        payload: {
          name: chunk[0].tool_call.name,
          result: JSON.parse(chunk[0].content),
        },
      };
    }

    res.write(`event:${eventType}\n`);
    res.write(`data:${JSON.stringify(messsage)}\n\n`);
  }

  res.end();
});

app.listen(4100, () => {
  console.log('Server is running on port 4100 Host: http://localhost:4100');
});
